
from building import *
import rtconfig

cwd     = GetCurrentDir()
src     = Glob('mdns.c')
LOCAL_CCFLAGS = ''

if rtconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=c99'
elif rtconfig.CROSS_TOOL == 'keil':
    LOCAL_CCFLAGS += ' --c99'

group = DefineGroup('mdns', src, depend = [], LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')

